USE [W_GnBD]
ALTER INDEX ALL ON SQBCONVOCATORIA
REBUILD;
ALTER INDEX ALL ON SQBEXERCICIO
REBUILD;
ALTER INDEX ALL ON SQBPRESENCA
REBUILD;
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON SQBTREINADOR
REBUILD;
ALTER INDEX ALL ON SQBJOGO
REBUILD;
ALTER INDEX ALL ON SQBTREINO
REBUILD;
ALTER INDEX ALL ON SQBCLUBE
REBUILD;
ALTER INDEX ALL ON SQBJOGADOR
REBUILD;
GO